UI(conversations): Fix comments looking the same
un/inbox pull request #359
Opened 2024-04-23 18:01 UTC by Flo4604

## What does this PR do?
:black_heart: 

This Fixes #355, comments should be able to be differentiated from Norma Emails. 
They are now displayed in a light blue color and black text which is not close to the actual conversation.
![49330](https://github.com/un/inbox/assets/53355483/05869ce9-450c-4c07-a953-d9159d08ba56)

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### Required

- [X] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Tested my code in a local environment
- [X] Commented on my code in hard-to-understand areas
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [X] If a UI change was made: Added a screen recording or screenshots to this PR
- [X] Updated the UnInbox Docs if changes were necessary

2024-04-23 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/un/inbox?pullRequest=359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/un/inbox?pullRequest=359) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/un/inbox?pullRequest=359) it.</sub>

2024-04-23 18:19 UTC, McPizza0 requested changes

2024-04-23 18:19 UTC, McPizza0 commented on apps/web-app/components/convos/convoMessageItem.vue
> -    }
we need to keep this to mark the user's own messages in blue
i would suggest copying the below `switch / case` block here to only change the styling if the current user is the author of the message

2024-04-23 18:19 UTC, McPizza0 commented on apps/web-app/components/convos/convoMessageItem.vue
> +        return 'bg-blue-5 text-black bg-base-4 text-base-12 ';
once we've copied the switch case block to the `if (userIsAuthor.value)` check, we would need to revert these

2024-04-24 07:17 UTC, Flo4604 commented
Made requested changes, 
<img width="740" alt="62602" src="https://github.com/un/inbox/assets/53355483/7c8836a6-bc20-4900-912f-68d311436c79">
<img width="791" alt="89131" src="https://github.com/un/inbox/assets/53355483/5cae71b7-44d4-4aef-bf5b-4461d344a351">

Now looks like this.

2024-04-25 12:43 UTC, McPizza0 approved these changes

2024-04-25 13:13 UTC, merged