feat: port `@u22n/storage` to Hono
un/inbox pull request #363
Opened 2024-04-26 18:57 UTC by BlankParticle

## What does this PR do?

Fixes # (issue)

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

2024-04-26 18:57 UTC, BlankParticle commented
* **#363** <a href="https://app.graphite.dev/github/pr/un/inbox/363?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BlankParticle and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-28 11:05 UTC, McPizza0 requested changes

2024-04-28 11:05 UTC, McPizza0 commented on apps/storage/src/app.ts
> +  .get(
why is this chained?
I would rather it was app.get per route to make it easier to skim through

2024-04-28 11:05 UTC, McPizza0 commented on apps/storage/src/app.ts
> +  .post(
same here
lets not chain
makes it easier to parse and move things around later

2024-04-28 11:05 UTC, McPizza0 commented on apps/storage/src/app.ts
> +  .get(
same

2024-04-28 11:05 UTC, McPizza0 commented on apps/storage/src/app.ts
> +  .post(
s

2024-04-29 11:29 UTC, McPizza0 approved these changes

2024-04-29 11:30 UTC, merged