feat(web): Convo View
un/inbox pull request #485
Opened 2024-05-29 17:20 UTC by McPizza0

## What does this PR do?

Fixes # (issue)

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

2024-05-29 17:20 UTC, McPizza0 commented
* **#485** <a href="https://app.graphite.dev/github/pr/un/inbox/485?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @McPizza0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-18 03:44 UTC, BlankParticle commented
![image](https://github.com/un/inbox/assets/130567419/9d57cc7c-ebf7-4ae0-b8bc-b85bbc3cd038)
There is extra whitespace in the convos list as the grid is divided in 3 cols and convos list occupies 1/3 of that, but the convos list has a max width which causes the issue

2024-06-18 03:47 UTC, BlankParticle commented
![image](https://github.com/un/inbox/assets/130567419/790241a7-5881-4f50-a294-aac2af8f8d6d)
while having more messages the send sections goes out of the screen

2024-06-18 04:05 UTC, BlankParticle requested changes

2024-06-18 04:05 UTC, BlankParticle commented on apps/web/src/components/avatar.tsx
> +      <span className="">{text()}</span>
Same as the last comment, call them like `<Icon/>` and `<Text/>` or you can also calculate the value and store them in `icon` and use it like `{icon}` not calling as function

2024-06-18 04:05 UTC, BlankParticle commented on apps/web/src/components/shared/attachments.tsx
> +          {icon()}
this too

2024-06-19 11:13 UTC, McPizza0 commented
@BlankParticle updated

2024-06-19 11:44 UTC, BlankParticle approved these changes
Message UI overflow issues aside, LGTM

2024-06-19 11:44 UTC, merged

2024-06-19 11:44 UTC, McPizza0 commented
### Merge activity

* **Jun 19, 7:44 AM EDT**: @McPizza0 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/un/inbox/485).