chore: improve app layout with auto reties and manual retry buttons
un/inbox pull request #613
Opened 2024-07-25 13:37 UTC by BlankParticle

## What does this PR do?

Fixes # (issue)

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

2024-07-25 13:37 UTC, BlankParticle commented
* **#613** <a href="https://app.graphite.dev/github/pr/un/inbox/613?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BlankParticle and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-26 05:30 UTC, McPizza0 commented on apps/web/src/app/[orgShortcode]/layout.tsx
> +        <span className="text-slate-11 font-bold">UnInbox is Loading...</span>
we should always wrap `UnInbox` in a span with `font-display` so it shows our logo
can you try this and send a screenshot for confirmation please

2024-07-26 05:31 UTC, McPizza0 requested changes
`UnInbox`  font change

2024-07-26 08:08 UTC, BlankParticle commented
<img width="426" alt="image" src="https://github.com/user-attachments/assets/7d74b043-8fba-454b-8133-b732c9d1557d">

2024-07-27 18:32 UTC, McPizza0 approved these changes

2024-07-27 18:33 UTC, merged

2024-07-27 18:33 UTC, McPizza0 commented
### Merge activity

* **Jul 27, 2:33 PM EDT**: @McPizza0 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/un/inbox/613).