modal changes
un/inbox pull request #621
Opened 2024-07-29 18:12 UTC by Esther-Lita

## What does this PR do?

Fixes # (issue)

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

2024-07-29 18:13 UTC, Esther-Lita commented
* **#621** <a href="https://app.graphite.dev/github/pr/un/inbox/621?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Esther-Lita and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-30 09:33 UTC, BlankParticle commented on apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/_components/add-address-modal.tsx
> +import { DialogClose } from '@radix-ui/react-dialog';
import from `@/src/components/shadcn-ui/switch` from `@radix-ui/*`

2024-07-30 09:34 UTC, BlankParticle commented on apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/_components/add-external-email-modal.tsx
> +export default function ExternalEmailModal({
don't use `default` export, it has issues with names while importing

2024-07-30 09:36 UTC, BlankParticle requested changes
Also check CI and fix those errors

2024-07-31 13:40 UTC, BlankParticle approved these changes

2024-07-31 13:41 UTC, merged